version: "3.9"

services:
  app:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/

  migrations:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c 'python3 manage.py makemigrations && python3 manage.py migrate'
    depends_on:
      db:
        condition: service_healthy



  db:
    image: postgres:15-alpine
    container_name: books_library
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
